//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natural
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Pasport { get; set; }
        public Nullable<int> INN { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Phone { get; set; }
        public string E_mail { get; set; }
    }
}
