//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natural
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cosmetic
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public System.DateTime Date_manu { get; set; }
        public System.DateTime Expiration { get; set; }
        public int Price { get; set; }
        public byte[] Image { get; set; }
    }
}
