//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natural
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public int Pasport { get; set; }
        public int Phone { get; set; }
        public int Selery { get; set; }
        public int INN { get; set; }
        public string E_mail { get; set; }
    }
}
